### ISSUE TITLE
Will Google Cloud Platform also work?

### ISSUE THREAD

**Issue by Cryptoseen** [IAMtheIAM/autoview-tradingview-chrome-docker-bot#1]
Hi, Will Google Cloud Platform also work? What should I do?

How do the alerts work? For example, is there a triggering pattern

Is it possible to get x coin using 0.1 BTC in a portfolio with 1 BTC?   

I'm sorry for my bad english. Thank you

**Comment by IAMtheIAM** [comment]
Hi there

If you use a service that has `Docker` enabled within google cloud platform then it will work fine. This specific repo is intented to be installed on an Ubuntu 16.04 server with Docker and Docker-compose installed.

The alerts are coming from tradingview.com alerts - this repo does not create or affect any alerts. They must be configured without your tradingview.com account which triggers the alert that the `Autoview` program inside this project understands. Autoview makes the API call to your exchange.

You can perform any trade that the exchange you use allows, [Autoview documentation](https://autoview.with.pink/#syntax)
