### ISSUE TITLE
sh: line 2: ./launch-virtual-display.sh: Permission denied

### ISSUE THREAD

**Issue by LarryEitel** [IAMtheIAM/autoview-tradingview-chrome-docker-bot#2]
Taking your auto-view docker for a spin. 

root@algo1:~/algo# docker-compose up
Recreating algo_virtual-display_1 ... done
Attaching to algo_virtual-display_1
virtual-display_1  | Starting Virtual Display Server...
virtual-display_1  | sh: line 2: **./launch-virtual-display.sh: Permission denied**
algo_virtual-display_1 exited with code 126

**Comment by IAMtheIAM** [comment]
Hi there. Make sure you do this 
`sudo docker-compose up`

You forgot to `sudo`

Check [instructions](https://github.com/IAMtheIAM/autoview-tradingview-chrome-docker-bot/blob/master/README.md) on this repo for stepy by step guidance

**Comment by LarryEitel** [comment]
I was running as root.

**Comment by IAMtheIAM** [comment]
`./launch-virtual-display.sh`  is a standard bash script, therefore it should run as any other. I would try running `sudo` as described. Without more info, about your server env, its hard to offer more help. Are you running Ubuntu 17+?

**Comment by LarryEitel** [comment]
I was using Ubuntu 18+.

I regularly run ANY command as root without sudo.

In either case, I opt'ed for a Vulr Windows VM.

So I am no longer involved in this issue.

Thank you for posting your project for me to try out.
