### ISSUE TITLE
-Any existing trade bots developed by you for crypto-currency.?

### ISSUE THREAD

**Issue by amebamcare** [IAMtheIAM/autoview-tradingview-chrome-docker-bot#3]
@IAMtheIAM  as a bot developer please contact me  for any future projects/already  developed by you and  let us have further business on these type of trade bots development. If you have any bots already please let me know PM me via my email ..Thanks

**Comment by IAMtheIAM** [comment]
Hello. Thanks for the message. I will send you an email.
