### ISSUE TITLE
sh: line 2: ./launch-virtual-display.sh: Permission denied

### ISSUE THREAD

**Issue by tech18** [IAMtheIAM/autoview-tradingview-chrome-docker-bot#4]
I'm using with "sudo" in the command but still receiving the below error:

**virtual-display_1_d60bbf8ed85d | sh: line 2: ./launch-virtual-display.sh: Permission denied**

![image](https://user-images.githubusercontent.com/1682659/46758390-55e0a780-ccea-11e8-8e7c-cc25f109d43c.png)

**Comment by IAMtheIAM** [comment]
This should be fixed with the latest commit. I added `sudo` to the docker-compose entry point. Let me know if it works.
